/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SongTi24.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x8FC8 (36808)                                *
* Character enabled:   0x9AD8 (39640)                                *
* Character enabled:   0x673A (26426)                                *
* Character enabled:   0x5668 (22120)                                *
* Character enabled:   0x4EBA (20154)                                *
* Character enabled:   0x519C (20892)                                *
* Character enabled:   0x4E1A (19994)                                *
* Character enabled:   0x7BA1 (31649)                                *
* Character enabled:   0x7406 (29702)                                *
* Character enabled:   0x7CF8 (31992)                                *
* Character enabled:   0x7EDF (32479)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSongTi24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_4E1A[ 72] = { /* code 4E1A */
  ________,________,________,
  ________,________,________,
  ________,_X____X_,________,
  ________,_X____X_,________,
  ________,_X____X_,________,
  ________,_X____X_,________,
  ________,_X____X_,________,
  __X_____,_X____X_,____X___,
  __X_____,_X____X_,____XX__,
  ___X____,_X____X_,___XX___,
  ____X___,_X____X_,___X____,
  ____XX__,_X____X_,__XX____,
  ____XX__,_X____X_,__X_____,
  _____XX_,_X____X_,_XX_____,
  _____XX_,_X____X_,_X______,
  _____XX_,_X____X_,X_______,
  ______X_,_X____XX,________,
  ________,_X____XX,________,
  ________,_X____X_,________,
  ________,_X____X_,________,
  ________,_X____X_,____XX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_4EBA[ 72] = { /* code 4EBA */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__X__X__,________,
  ________,__X__X__,________,
  ________,_XX__X__,________,
  ________,_XX___X_,________,
  ________,_X____X_,________,
  ________,XX____XX,________,
  ________,X______X,X_______,
  _______X,X_______,X_______,
  ______XX,________,XX______,
  _____XX_,________,_XXX____,
  ____XX__,________,__XXXX__,
  ___X____,________,___XXX__,
  __X_____,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_519C[ 72] = { /* code 519C */
  ________,________,________,
  ________,___X____,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___X____,________,
  ____X___,__XX____,___X____,
  ____XXXX,XXXXXXXX,XXXXX___,
  ___XX___,__XX____,__XX____,
  ___XX___,_XXX____,_X______,
  __XX____,_X__X___,________,
  ________,XX__X___,__X_____,
  ________,X___X___,_XXX____,
  _______X,X____X__,XX______,
  ______XX,X____X_X,________,
  ______XX,X_____X_,________,
  _____X_X,X_____XX,________,
  ____X__X,X______X,________,
  ___X___X,X_______,XX______,
  __X____X,X____X__,XXX_____,
  _X_____X,X__XX___,_XXXX___,
  _______X,XXX_____,___XXXX_,
  _______X,XX______,____X___,
  ________,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_5668[ 72] = { /* code 5668 */
  ________,________,________,
  ________,________,________,
  ____X___,_____X__,________,
  ____XXXX,XXX__XXX,XXXX____,
  ____XX__,_XX__XX_,__XX____,
  ____XX__,_XX__XX_,__XX____,
  ____XX__,_XX__XX_,__XX____,
  ____XXXX,XXX__XXX,XXXX____,
  ____XX__,_XX__XX_,__X_____,
  ________,__XXX__X,XX______,
  ________,__X_____,_X__X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,XX____X_,________,
  _______X,X______X,X_______,
  ______XX,________,XXX_____,
  ____XX__,__X_____,__XXXXX_,
  __XX_XXX,XXX__XXX,XXXXX___,
  _____X__,_XX__X__,__XX____,
  _____X__,_XX__X__,__XX____,
  _____X__,_XX__X__,__XX____,
  _____XXX,XXX__XXX,XXXX____,
  _____X__,_XX__X__,__XX____,
  ____X___,_____X__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_673A[ 72] = { /* code 673A */
  ________,________,________,
  _____X__,________,________,
  _____XX_,________,________,
  _____X__,___X____,_XX_____,
  _____X__,___XXXXX,XXX_____,
  _____X__,___XX___,_X______,
  _____X__,___XX___,_X______,
  _XXXXXXX,XX_XX___,_X______,
  _____X__,___XX___,_X______,
  _____X__,___XX___,_X______,
  ____XXX_,___XX___,_X______,
  ____XX_X,X__XX___,_X______,
  ____XX__,XX_XX___,_X______,
  ___XXX__,_X_XX___,_X______,
  ___X_X__,___XX___,_X______,
  ___X_X__,___X____,_X______,
  __X__X__,___X____,_X______,
  _X___X__,___X____,_X___X__,
  _____X__,__XX____,_X___X__,
  _____X__,__X_____,_X___X__,
  _____XX_,_X______,_XX__XX_,
  _____XX_,X_______,_XXXXXX_,
  _____XXX,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_7406[ 72] = { /* code 7406 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXXX,XXXXX___,
  _______X,X__X___X,____X___,
  __XXXXX_,___X___X,____X___,
  _____X__,___X___X,____X___,
  _____X__,___X___X,____X___,
  _____X__,___XXXXX,XXXXX___,
  _____X__,___X___X,____X___,
  _____X__,X__X___X,____X___,
  __XXXXXX,___X___X,____X___,
  _____X__,___XXXXX,XXXXX___,
  _____X__,___X___X,____X___,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_X_____X,___XX___,
  _____XXX,X_XXXXXX,XXX_____,
  __XXXX__,_______X,________,
  __XX____,_______X,________,
  ________,_______X,_____X__,
  ________,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_7BA1[ 72] = { /* code 7BA1 */
  ________,________,________,
  _____X__,________,________,
  _____XX_,______XX,________,
  _____X__,______X_,____X___,
  ____XXXX,XXXX_XXX,XXXXXX__,
  ___XX__X,____X___,X_______,
  ___X___X,X__X____,_X______,
  __X____X,___XX___,_X______,
  ___X____,____X___,____XX__,
  ___XXXXX,XXXX_XXX,XXXXXXX_,
  __XX____,________,____X___,
  __X___XX,XXXXXXXX,XX_X____,
  ______X_,________,X_______,
  ______X_,________,X_______,
  ______X_,________,X_______,
  ______XX,XXXXXXXX,X_______,
  ______X_,________,________,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_7CF8[ 72] = { /* code 7CF8 */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,_XX_____,________,
  ________,XX______,XX______,
  _______X,_______X,X_______,
  ______X_,______X_,________,
  _____XXX,XXXXXX__,________,
  _____XX_,___XX___,________,
  ________,__XX___X,________,
  ________,_X______,XX______,
  _______X,X_______,_XX_____,
  _____XX_,_____XXX,XXXX____,
  ____XXXX,XXXXX___,___XX___,
  _____X__,____X___,___XX___,
  ________,____X___,________,
  _______X,XX__X__X,X_______,
  ______XX,____X___,_XX_____,
  _____XX_,____X___,__XXX___,
  ____XX__,____X___,___XX___,
  ___X____,_XXXX___,____X___,
  __X_____,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_7EDF[ 72] = { /* code 7EDF */
  ________,________,________,
  ________,________,________,
  ______XX,______XX,________,
  _____XX_,_______X,X_______,
  _____X__,_______X,____X___,
  ____XX__,__XXXXXX,XXXXXX__,
  ____X___,X_____XX,________,
  ___X____,XX____X_,________,
  __X____X,X____X__,________,
  __XXXXXX,____X___,_XX_____,
  ______X_,___X____,___XX___,
  _____X__,__XXXXXX,XXXXXX__,
  ____X___,__XXXXX_,_X__XX__,
  ___X____,_X___X__,_X______,
  __XXXXXX,X____X__,_X______,
  ___X____,_____X__,_X______,
  ________,_____X__,_X______,
  ________,_X___X__,_X______,
  _____XXX,X___XX__,_X___X__,
  __XXX___,____X___,_X___X__,
  __X_____,___XX___,_X___X__,
  ________,__X_____,_XXXXXX_,
  ________,XX______,__XXXX__,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_8FC8[ 72] = { /* code 8FC8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,________,____X___,
  ____X___,XXXXXXXX,XXXX____,
  ____X___,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  _____X__,____XXXX,XXXXX___,
  _XXXXXX_,___XX___,___X____,
  _____X__,___XX___,__XX____,
  _____X__,___X____,__XX____,
  _____X__,___X____,__XX____,
  _____X__,___X____,__X_____,
  _____X__,__X_____,__X_____,
  _____X__,__X_____,__X_____,
  _____X__,_X______,__X_____,
  _____X__,X______X,XXX_____,
  ____X_XX,________,XX______,
  __XX___X,________,________,
  _XX_____,XXX_____,______X_,
  ________,__XXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSongTi24_9AD8[ 72] = { /* code 9AD8 */
  ________,________,________,
  ________,__X_____,________,
  ________,___X____,________,
  ________,___XX___,________,
  ________,________,____XX__,
  ___XXXXX,XXXXXXXX,XXXX____,
  ______X_,________,X_______,
  ______XX,XXXXXXXX,XX______,
  ______XX,________,X_______,
  ______XX,________,X_______,
  ______XX,XXXXXXXX,X_______,
  ______X_,________,X_______,
  ___X____,________,____X___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,_______X,___XX___,
  ___XX___,XXXXXXXX,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,XXXXXXXX,___XX___,
  ___XX___,________,___XX___,
  ___XX___,________,XXXXX___,
  ___XX___,________,___XX___,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSongTi24_CharInfo[11] = {
   {  24,  24,  3, acGUI_FontSongTi24_4E1A } /* code 4E1A */
  ,{  24,  24,  3, acGUI_FontSongTi24_4EBA } /* code 4EBA */
  ,{  24,  24,  3, acGUI_FontSongTi24_519C } /* code 519C */
  ,{  24,  24,  3, acGUI_FontSongTi24_5668 } /* code 5668 */
  ,{  24,  24,  3, acGUI_FontSongTi24_673A } /* code 673A */
  ,{  24,  24,  3, acGUI_FontSongTi24_7406 } /* code 7406 */
  ,{  24,  24,  3, acGUI_FontSongTi24_7BA1 } /* code 7BA1 */
  ,{  24,  24,  3, acGUI_FontSongTi24_7CF8 } /* code 7CF8 */
  ,{  24,  24,  3, acGUI_FontSongTi24_7EDF } /* code 7EDF */
  ,{  24,  24,  3, acGUI_FontSongTi24_8FC8 } /* code 8FC8 */
  ,{  24,  24,  3, acGUI_FontSongTi24_9AD8 } /* code 9AD8 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop11 = {
   0x9AD8 /* first character */
  ,0x9AD8 /* last character  */
  ,&GUI_FontSongTi24_CharInfo[ 10] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop10 = {
   0x8FC8 /* first character */
  ,0x8FC8 /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  9] /* address of first character */
  ,&GUI_FontSongTi24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop9 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  8] /* address of first character */
  ,&GUI_FontSongTi24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop8 = {
   0x7CF8 /* first character */
  ,0x7CF8 /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  7] /* address of first character */
  ,&GUI_FontSongTi24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop7 = {
   0x7BA1 /* first character */
  ,0x7BA1 /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  6] /* address of first character */
  ,&GUI_FontSongTi24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop6 = {
   0x7406 /* first character */
  ,0x7406 /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  5] /* address of first character */
  ,&GUI_FontSongTi24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop5 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  4] /* address of first character */
  ,&GUI_FontSongTi24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop4 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  3] /* address of first character */
  ,&GUI_FontSongTi24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop3 = {
   0x519C /* first character */
  ,0x519C /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  2] /* address of first character */
  ,&GUI_FontSongTi24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop2 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  1] /* address of first character */
  ,&GUI_FontSongTi24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSongTi24_Prop1 = {
   0x4E1A /* first character */
  ,0x4E1A /* last character  */
  ,&GUI_FontSongTi24_CharInfo[  0] /* address of first character */
  ,&GUI_FontSongTi24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSongTi24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSongTi24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

