/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti16.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Character enabled:   0x209 (521)                                   *
* Character disabled:  0x209 (521)                                   *
* Character enabled:   0x8FC8 (36808)                                *
* Character enabled:   0x9AD8 (39640)                                *
* Character enabled:   0x673A (26426)                                *
* Character enabled:   0x5668 (22120)                                *
* Character enabled:   0x4EBA (20154)                                *
* Character enabled:   0x4E1A (19994)                                *
* Character enabled:   0x519C (20892)                                *
* Character enabled:   0x7406 (29702)                                *
* Character enabled:   0x7CF8 (31992)                                *
* Character enabled:   0x7EDF (32479)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0022[ 16] = { /* code 0022, QUOTATION MARK */
  ________,
  ___X__X_,
  __XX_XX_,
  __X__X__,
  _X__X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0023[ 16] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  __X__X__,
  __X__X__,
  __X__X__,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXX___,
  _X_X_X__,
  _X_X_X__,
  _X_X____,
  __XX____,
  ___XX___,
  ___X_X__,
  ___X_X__,
  _X_X_X__,
  _X_X_X__,
  __XXX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0025[ 16] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  __X_X_X_,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0026[ 16] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X_X____,
  _XX_XXX_,
  X_X__X__,
  X__X_X__,
  X___X___,
  X___X__X,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0027[ 16] = { /* code 0027, APOSTROPHE */
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  _X______,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002A[ 16] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  XX_X_XX_,
  __XXX___,
  __XXX___,
  XX_X_XX_,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  _______X,
  ______X_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003D[ 16] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003F[ 16] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _XX___X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0040[ 16] = { /* code 0040, COMMERCIAL AT */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X_XX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XX_X__,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X___XXX_,
  X____X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  __XXXXX_,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  XX___XXX,
  _XX___X_,
  _XX___X_,
  _X_X__X_,
  _X_X__X_,
  _X__X_X_,
  _X__X_X_,
  _X__X_X_,
  _X___XX_,
  _X___XX_,
  XXX___X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_XX__X_,
  XX__X_X_,
  _X__XX__,
  __XXX___,
  _____XX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  _X____X_,
  XXX___XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X______,
  __X_____,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X___X__,
  __X__X__,
  __X__X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  ________,
  XX_X_XX_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _XX_XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  _XXXXXX_,
  X____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005B[ 16] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XXXX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  _____X__,
  ______X_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005D[ 16] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ___XXX__,
  __X___X_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005F[ 16] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  ________,
  _XX_____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  __XXXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  _X______,
  _X______,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  _____XX_,
  ______X_,
  ______X_,
  ______X_,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _XXXXXX_,
  _X______,
  _X______,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ____XXXX,
  ___X___X,
  ___X____,
  ___X____,
  _XXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXX___,
  _X______,
  __XXXX__,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ___XXX__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _X___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  XXX_XX_X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X___X_,
  ___XXXX_,
  ______X_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X______,
  __XXXX__,
  ______X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_X_XXX,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _X___X__,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XXX_,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  ____X___,
  ___X____,
  ___X____,
  __X___X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ______XX,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  ____X___,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  ______XX,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007C[ 16] = { /* code 007C, VERTICAL LINE */
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  _XX_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007E[ 16] = { /* code 007E, TILDE */
  __XX____,
  _X__XX__,
  _X____XX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007F[ 16] = { /* code 007F, <control> */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4E1A[ 32] = { /* code 4E1A */
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  _X___X__,_X___X__,
  __X__X__,_X___X__,
  __X__X__,_X__X___,
  ___X_X__,_X__X___,
  ___X_X__,_X_X____,
  ___X_X__,_XX_____,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4EBA[ 32] = { /* code 4EBA */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  _X______,_____X__,
  X_______,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_519C[ 32] = { /* code 519C */
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _X____X_,_____X__,
  X_____X_,____X___,
  _____X_X,________,
  _____X_X,____X___,
  ____X___,X__X____,
  ___XX___,X_X_____,
  __X_X___,_X______,
  _X__X___,__X_____,
  X___X___,___X____,
  ____X_X_,____X___,
  ____XX__,_____XX_,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5668[ 32] = { /* code 5668 */
  ________,________,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  _______X,__X_____,
  _______X,___X____,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_673A[ 32] = { /* code 673A */
  ___X____,________,
  ___X___X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  XXXXXX_X,___X____,
  ___X___X,___X____,
  __XX___X,___X____,
  __XXX__X,___X____,
  _X_X_X_X,___X____,
  _X_X_X_X,___X____,
  X__X___X,___X____,
  ___X___X,___X__X_,
  ___X___X,___X__X_,
  ___X__X_,___X__X_,
  ___X__X_,____XXX_,
  ___X_X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7406[ 32] = { /* code 7406 */
  ________,________,
  _______X,XXXXXX__,
  XXXXXX_X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,XXXXXX__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  _XXXXX_X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,XXXXXX__,
  ___X____,__X_____,
  ___XXX__,__X_____,
  XXX_____,__X_____,
  _X____XX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7CF8[ 32] = { /* code 7CF8 */
  ______X_,________,
  _____X__,________,
  ____X___,__X_____,
  ___X____,_X______,
  __XXXXXX,X_______,
  _______X,________,
  _____XX_,___X____,
  ___XX___,____X___,
  _XXXXXXX,XXXXXX__,
  _______X,_____X__,
  ____X__X,__X_____,
  ____X__X,___X____,
  ___X___X,____X___,
  __X____X,_____X__,
  _X___X_X,_____X__,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7EDF[ 32] = { /* code 7EDF */
  ___X____,_X______,
  ___X____,__X_____,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  _X__X___,_X______,
  XXXXX___,X___X___,
  ___X___X,_____X__,
  __X___XX,XXXXXXX_,
  _X______,X__X__X_,
  XXXXX___,X__X____,
  _X______,X__X____,
  ________,X__X____,
  ___XX__X,___X__X_,
  XXX____X,___X__X_,
  _X____X_,____XXX_,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8FC8[ 32] = { /* code 8FC8 */
  ________,________,
  __X_____,________,
  ___X_XXX,XXXXXXX_,
  ___X____,X_______,
  ________,X_______,
  ________,XXXXXX__,
  XXXX____,X____X__,
  ___X____,X____X__,
  ___X____,X____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X__X_,__X_X___,
  ___X_X__,___X____,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_9AD8[ 32] = { /* code 9AD8 */
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ____XXXX,XXX_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____XXXX,XXX_____,
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__,
  _X__XXXX,XXX__X__,
  _X__X___,__X__X__,
  _X__X___,__X__X__,
  _X__XXXX,XXX__X__,
  _X______,____XX__};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti16_CharInfo[106] = {
   {   8,   8,  1, acGUI_Fontsongti16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_Fontsongti16_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_Fontsongti16_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_Fontsongti16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_Fontsongti16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontsongti16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Fontsongti16_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fontsongti16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_Fontsongti16_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_Fontsongti16_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_Fontsongti16_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_Fontsongti16_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_Fontsongti16_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_Fontsongti16_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_Fontsongti16_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_Fontsongti16_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_Fontsongti16_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_Fontsongti16_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_Fontsongti16_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_Fontsongti16_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_Fontsongti16_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_Fontsongti16_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_Fontsongti16_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_Fontsongti16_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_Fontsongti16_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_Fontsongti16_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_Fontsongti16_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_Fontsongti16_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_Fontsongti16_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_Fontsongti16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Fontsongti16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_Fontsongti16_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_Fontsongti16_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_Fontsongti16_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_Fontsongti16_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_Fontsongti16_007E } /* code 007E */
  ,{   8,   8,  1, acGUI_Fontsongti16_007F } /* code 007F */
  ,{  16,  16,  2, acGUI_Fontsongti16_4E1A } /* code 4E1A */
  ,{  16,  16,  2, acGUI_Fontsongti16_4EBA } /* code 4EBA */
  ,{  16,  16,  2, acGUI_Fontsongti16_519C } /* code 519C */
  ,{  16,  16,  2, acGUI_Fontsongti16_5668 } /* code 5668 */
  ,{  16,  16,  2, acGUI_Fontsongti16_673A } /* code 673A */
  ,{  16,  16,  2, acGUI_Fontsongti16_7406 } /* code 7406 */
  ,{  16,  16,  2, acGUI_Fontsongti16_7CF8 } /* code 7CF8 */
  ,{  16,  16,  2, acGUI_Fontsongti16_7EDF } /* code 7EDF */
  ,{  16,  16,  2, acGUI_Fontsongti16_8FC8 } /* code 8FC8 */
  ,{  16,  16,  2, acGUI_Fontsongti16_9AD8 } /* code 9AD8 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop11 = {
   0x9AD8 /* first character */
  ,0x9AD8 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[105] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop10 = {
   0x8FC8 /* first character */
  ,0x8FC8 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[104] /* address of first character */
  ,&GUI_Fontsongti16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop9 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_Fontsongti16_CharInfo[103] /* address of first character */
  ,&GUI_Fontsongti16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop8 = {
   0x7CF8 /* first character */
  ,0x7CF8 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[102] /* address of first character */
  ,&GUI_Fontsongti16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop7 = {
   0x7406 /* first character */
  ,0x7406 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[101] /* address of first character */
  ,&GUI_Fontsongti16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop6 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[100] /* address of first character */
  ,&GUI_Fontsongti16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop5 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontsongti16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop4 = {
   0x519C /* first character */
  ,0x519C /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontsongti16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop3 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontsongti16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop2 = {
   0x4E1A /* first character */
  ,0x4E1A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontsongti16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

