/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: wenshiduSongTi16.c                                    *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character enabled:   0x7B2C (31532)                                *
* Character enabled:   0x8282 (33410)                                *
* Character disabled:  0x7B2C (31532)                                *
* Character enabled:   0x70B9 (28857)                                *
* Character enabled:   0x7A7A (31354)                                *
* Character enabled:   0x6C14 (27668)                                *
* Character enabled:   0x58E4 (22756)                                *
* Character enabled:   0x571F (22303)                                *
* Character enabled:   0x6E29 (28201)                                *
* Character enabled:   0x5EA6 (24230)                                *
* Character enabled:   0x6E7F (28287)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontwenshiduSongTi16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_____};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_571F[ 32] = { /* code 571F */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_58E4[ 32] = { /* code 58E4 */
  __X_____,_X______,
  __X__XXX,XXXXXX__,
  __X_____,________,
  __X___XX,X_XXX___,
  XXXX__X_,X_X_X___,
  __X___XX,X_XXX___,
  __X____X,___X____,
  __X__XXX,XXXXXX__,
  __X____X,___X____,
  __X__XXX,XXXXXX__,
  __XX___X,___X____,
  XXX_XXXX,XXXXXXX_,
  _X_____X,__X_X___,
  ______XX,___X____,
  ____XX_X,_X__X___,
  _______X,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXXXXX__,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXX_____,
  __X_____,________,
  __X_XXXX,XXXX____,
  __X__X__,___X____,
  _X____X_,__X_____,
  _X_____X,XX______,
  X____XX_,__XX____,
  __XXX___,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_6C14[ 32] = { /* code 6C14 */
  ___X____,________,
  ___X____,________,
  __XXXXXX,XXXXXX__,
  __X_____,________,
  _X__XXXX,XXXX____,
  X_______,________,
  __XXXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,____X_X_,
  ________,____X_X_,
  ________,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_6E29[ 32] = { /* code 6E29 */
  ________,________,
  __X___XX,XXXXX___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  X_____XX,XXXXX___,
  _X____X_,____X___,
  _X____X_,____X___,
  ___X__XX,XXXXX___,
  ___X____,________,
  __X__XXX,XXXXXX__,
  XXX__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_6E7F[ 32] = { /* code 6E7F */
  ________,________,
  __X__XXX,XXXXX___,
  ___X_X__,____X___,
  ___X_X__,____X___,
  X____XXX,XXXXX___,
  _X___X__,____X___,
  _X___X__,____X___,
  ___X_XXX,XXXXX___,
  ___X___X,__X_____,
  __X____X,__X_____,
  XXX_X__X,__X__X__,
  __X__X_X,__X_X___,
  __X___XX,__XX____,
  __X____X,__X_____,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_70B9[ 32] = { /* code 70B9 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXXX__,
  ______X_,________,
  ______X_,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  ________,________,
  __X__X__,X___X___,
  __X___X_,_X___X__,
  _X____X_,_X___X__,
  X_______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_7A7A[ 32] = { /* code 7A7A */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X___X___,__X__X__,
  ___X____,___X____,
  __X_____,____X___,
  ________,________,
  ___XXXXX,XXXX____,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontwenshiduSongTi16_8282[ 32] = { /* code 8282 */
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ____X___,__X_____,
  ________,________,
  _XXXXXXX,XXXXX___,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,_X_X____,
  ______X_,__X_____,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontwenshiduSongTi16_CharInfo[21] = {
   {   8,   8,  1, acGUI_FontwenshiduSongTi16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_FontwenshiduSongTi16_003B } /* code 003B */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_571F } /* code 571F */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_58E4 } /* code 58E4 */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_6C14 } /* code 6C14 */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_6E29 } /* code 6E29 */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_6E7F } /* code 6E7F */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_70B9 } /* code 70B9 */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_7A7A } /* code 7A7A */
  ,{  16,  16,  2, acGUI_FontwenshiduSongTi16_8282 } /* code 8282 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop10 = {
   0x8282 /* first character */
  ,0x8282 /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 20] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop9 = {
   0x7A7A /* first character */
  ,0x7A7A /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 19] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop8 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 18] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop7 = {
   0x6E7F /* first character */
  ,0x6E7F /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 17] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop6 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 16] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop5 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 15] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop4 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 14] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop3 = {
   0x58E4 /* first character */
  ,0x58E4 /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 13] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop2 = {
   0x571F /* first character */
  ,0x571F /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[ 12] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontwenshiduSongTi16_Prop1 = {
   0x0030 /* first character */
  ,0x003B /* last character  */
  ,&GUI_FontwenshiduSongTi16_CharInfo[  0] /* address of first character */
  ,&GUI_FontwenshiduSongTi16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontwenshiduSongTi16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontwenshiduSongTi16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

