/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: zhandian16.c                                          *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0030 - 003F                                  *
* Range enabled:        0024 - 003F                                  *
* Character enabled:   0x2103 (8451)                                 *
* Character enabled:   0x2109 (8457)                                 *
* Range enabled:        7AD9 - 7AD9                                  *
* Range enabled:        70B9 - 70B9                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontzhandian16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXX___,
  _X_X_X__,
  _X_X_X__,
  _X_X____,
  __XX____,
  ___XX___,
  ___X_X__,
  ___X_X__,
  _X_X_X__,
  _X_X_X__,
  __XXX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0025[ 16] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  __X_X_X_,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0026[ 16] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X_X____,
  _XX_XXX_,
  X_X__X__,
  X__X_X__,
  X___X___,
  X___X__X,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0027[ 16] = { /* code 0027, APOSTROPHE */
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  _X______,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_002A[ 16] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  XX_X_XX_,
  __XXX___,
  __XXX___,
  XX_X_XX_,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  _______X,
  ______X_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_003D[ 16] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_003F[ 16] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _XX___X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

/* Start of unicode area <Letterlike Symbols> */
GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_2103[ 32] = { /* code 2103, DEGREE CELSIUS */
  _XX_____,________,
  X__X___X,XXXX_X__,
  X__X_XX_,____XX__,
  _XX_XX__,_____X__,
  ____X___,_____X__,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ____X___,________,
  ____XX__,_____X__,
  _____XX_,____X___,
  _______X,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_2109[ 32] = { /* code 2109, DEGREE FAHRENHEIT */
  ________,________,
  ______XX,XXXXXX__,
  ___XX__X,____XX__,
  __X__X_X,_____X__,
  __X__X_X,_____X__,
  ___XX__X,___X____,
  _______X,___X____,
  _______X,XXXX____,
  _______X,___X____,
  _______X,___X____,
  _______X,________,
  _______X,________,
  _______X,________,
  ______XX,X_______,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_70B9[ 32] = { /* code 70B9 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXXX__,
  ______X_,________,
  ______X_,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  ________,________,
  __X__X__,X___X___,
  __X___X_,_X___X__,
  _X____X_,_X___X__,
  X_______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontzhandian16_7AD9[ 32] = { /* code 7AD9 */
  ___X____,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  _XXXXXX_,__X_____,
  ________,__XXXXX_,
  _____X__,__X_____,
  _X___X__,__X_____,
  _X___X__,__X_____,
  __X__X_X,XXXXXX__,
  __X_X__X,_____X__,
  __X_X__X,_____X__,
  ____XXXX,_____X__,
  XXXX___X,_____X__,
  _X_____X,_____X__,
  _______X,XXXXXX__,
  _______X,_____X__};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontzhandian16_CharInfo[32] = {
   {   8,   8,  1, acGUI_Fontzhandian16_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_Fontzhandian16_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_Fontzhandian16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_Fontzhandian16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontzhandian16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Fontzhandian16_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fontzhandian16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_Fontzhandian16_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_Fontzhandian16_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_Fontzhandian16_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_Fontzhandian16_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_Fontzhandian16_003F } /* code 003F */
  ,{  16,  16,  2, acGUI_Fontzhandian16_2103 } /* code 2103 */
  ,{  16,  16,  2, acGUI_Fontzhandian16_2109 } /* code 2109 */
  ,{  16,  16,  2, acGUI_Fontzhandian16_70B9 } /* code 70B9 */
  ,{  16,  16,  2, acGUI_Fontzhandian16_7AD9 } /* code 7AD9 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontzhandian16_Prop5 = {
   0x7AD9 /* first character */
  ,0x7AD9 /* last character  */
  ,&GUI_Fontzhandian16_CharInfo[ 31] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontzhandian16_Prop4 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_Fontzhandian16_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontzhandian16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontzhandian16_Prop3 = {
   0x2109 /* first character */
  ,0x2109 /* last character  */
  ,&GUI_Fontzhandian16_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontzhandian16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontzhandian16_Prop2 = {
   0x2103 /* first character */
  ,0x2103 /* last character  */
  ,&GUI_Fontzhandian16_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontzhandian16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontzhandian16_Prop1 = {
   0x0024 /* first character */
  ,0x003F /* last character  */
  ,&GUI_Fontzhandian16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontzhandian16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontzhandian16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontzhandian16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

